### ISSUE TITLE
Card Branding information

### ISSUE THREAD

**Issue by easycheese** [omise/omise-android#11]
Am I crazy or does 'requestToken' not include the card branding information?

**Comment by tinhanchanachai** [comment]
What omise-android do you use?.
I try on omise-android 1.0.3, Can get brand.
Token.getCare().getBrand();

Ref document for Token API : https://www.omise.co/tokens-api

**Comment by easycheese** [comment]
Sorry, I didn't realize that omise determined the brand from the card number, I thought we had to call setBrand()
