### ISSUE TITLE
Backward compatilibity

### ISSUE THREAD

**Issue by khunzohn** [omise/omise-android#12]
Hi team omise,
The current lib supports android 19 and up. Is there any possibility for android version prior to 19 to leverage this library?I'd like to go down as far as 15 in my case. If not ,what would be the solution for those old android versions? Thanks.

**Comment by chakrit** [comment]
@khunzohn Hi the requirement for version 19 was a conservative move by me. However, I have just tested most of the code as-is with `minSdkVersion 15` and everything seems to be working ok, so I have published version `2.0.1` with that change.

It should be available on maven central in a bit.

If you have more questions, feel free to ask away (or pop onto our gitter live chat: gitter.im/omise/omise-android)

**Comment by chakrit** [comment]
@khunzohn feel free to reopen if this does not fix your problem.
