### ISSUE TITLE
Android   Java  Code

### ISSUE THREAD

**Issue by zhangwenxiang26** [omise/omise-android#122]
Is there any Java code? This is all kotlin code for Android .

**Comment by nuxzero** [comment]
Yes, we support both Java and Kotlin. You can find different usage in the sample code of the project. 

If you have any questions, please don't hesitate to ask.

**Comment by zhangwenxiang26** [comment]
Oh sorry  . I can't find Java  code  usage in the sample  of the project. There is only Kotlin code .
For example,
-----------------------------------------------------------------------------------------------------------
val cardParam = CardParam(
                name = "JOHN Doe",
                number = "4242424242424242",
                expirationMonth = 10,
                expirationYear = 2020,
                securityCode = "123")

val request = Token.CreateTokenRequestBuilder(cardParam).build()
-----------------------------------------------------------------------------------------------------------
Where can I find Java code. I need help . 
@nuxzero

**Comment by nuxzero** [comment]
Unfortunately, we don't have this sample in the sample code. However, you can call Kotlin code in Java as regular Java conventional like this.

```
CardParam params = new CardParam(
                "JOHN Doe",
                "4242424242424242",
                10,
                2020,
                "123",
                null,
                null);
Request request = new Token.CreateTokenRequestBuilder(params).build();
```

Thank you for your feedback. We will note this to update in the future version.

**Comment by nuxzero** [comment]
If you have another question about this issue, please feel free to reopen it. 🙂
