### ISSUE TITLE
Could we have DomStorage enable from WebView in AuthorizingPaymentActivity?

### ISSUE THREAD

**Issue by luongvo** [omise/omise-android#141]
Same to the question above, could we have `DomStorage` enable from WebView in [AuthorizingPaymentActivity](https://github.com/omise/omise-android/blob/a9b8e638453baf68ea5a29e47b2ad4350945e629/sdk/src/main/java/co/omise/android/ui/AuthorizingPaymentActivity.kt#L30)? Or can you provide a way to enable DomStorage on AuthorizingPaymentActivity's WebView via Intent data 🤔 

The context is:
- Our authorizing uri and its redirection mechanism require to use DOM storage feature.
- Android Webview disables DOM storage by default.
- OmiseSDK has a built-in webview to take care of authorizing payment flow and this webview disables DOM storage by default too, that leads to the error below:
```
2020-07-29 17:41:48.469 14598-14598/co.omise.gcpf.app.staging I/chromium: [INFO:CONSOLE(1154)] "Uncaught TypeError: Cannot read property 'removeItem' of null", source: webpack:///../deps/phoenix_live_view/priv/static/phoenix_live_view.js? (1154)
```
`removeItem` comes from a dom sessionStorage.
![image](https://user-images.githubusercontent.com/16315358/88792522-8a766980-d1c5-11ea-9618-739ffe272e93.png)

I'm not sure if there is any security concerns to enable DOM storage on AuthorizingPaymentActivity's WebView
```
domStorageEnabled = true
```

**Comment by nuxzero** [comment]
@luongvo Thank you for raised this issue. This seems like the JavaScript can't work without enable `domStorageEnabled`. Anyway, we are working on this issue. So, we will let you if there is an update. 🙂

**Comment by nuxzero** [comment]
@luongvo We just release the version `3.1.2` that included enabling Dom Storage on the WebView. Please update your application to the latest version and the error should be gone.

If you have any question that related to this issue please feel free to re-open this issue and ask your questions. 🙂

**Comment by luongvo** [comment]
@nuxzero great, I will give it a try, thanks
