### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by zhangwenxiang26** [omise/omise-android#177]
**Android 5.1.1,level 22   --->  i-mobile IQ Z BRIGHT  ---> arm64-v8a **

String resource ID #0x2040003

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.xxx.xxx/co.omise.android.ui.AuthorizingPaymentActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class android.webkit.WebView

Caused by:
--
5 android.content.res.Resources$NotFoundException:String resource ID #0x2040003
6 android.content.res.Resources.getText(Resources.java:299)
7 android.content.res.Resources.getString(Resources.java:385)
8 com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
9 com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
10 com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
11 com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
12 com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
13 com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
14 com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:312)
15 com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
16 com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:264)
17 com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
18 com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
19 com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
20 com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
21 com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:261)
22 android.webkit.WebView.<init>(WebView.java:554)
23 android.webkit.WebView.<init>(WebView.java:489)
24 android.webkit.WebView.<init>(WebView.java:472)
25 android.webkit.WebView.<init>(WebView.java:459)
26 java.lang.reflect.Constructor.newInstance(Native Method)
27 java.lang.reflect.Constructor.newInstance(Constructor.java:288)
28 android.view.LayoutInflater.createView(LayoutInflater.java:607)
29 com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
30 android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
31 android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
32 android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
33 android.view.LayoutInflater.inflate(LayoutInflater.java:504)
34 android.view.LayoutInflater.inflate(LayoutInflater.java:414)
35 android.view.LayoutInflater.inflate(LayoutInflater.java:365)
36 androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:9)
37 androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:1)
38 co.omise.android.ui.AuthorizingPaymentActivity.onCreate(SourceFile:2)

**Comment by nuxzero** [comment]
@zhangwenxiang26 Thank you for your reports. I'll look into the issue. 🙂

**Comment by nuxzero** [comment]
@zhangwenxiang26  Please check out our new version 3.2.1 which included this bug fix. Please let us known if you face any issue.

**Comment by zhangwenxiang26** [comment]
Thank you. I will update to the app and wait for user feedback.
