### ISSUE TITLE
The SDK caused Glide to fail to load

### ISSUE THREAD

**Issue by qflbai** [omise/omise-android#193]
![image](https://user-images.githubusercontent.com/23705172/112131487-91defd00-8c04-11eb-8a8f-a2c700ff22f2.png)

**Comment by qflbai** [comment]
Anybody solve it?

**Comment by qflbai** [comment]
1、Omise SDK version：    implementation 'co.omise:omise-android:4.+'
2、Android version：10
3、Glide.with(this).load(skuPic).into(ivImage)

**Comment by nuxzero** [comment]
@qflbai Thank you for the information. We will raise this issue to our team then inform you if there's any update.

**Comment by nuxzero** [comment]
@qflbai Our team tried to reproduce this issue with your information. We have not found any issue that you raised. In my opinion this issue seems not related to Omise Android. However, could you provide a sample project with this issue for us?
