### ISSUE TITLE
How can i create customer by  Android library

### ISSUE THREAD

**Issue by daisyfoto** [omise/omise-android#2]
Hello Omise team
Thank you library for android
I try library for android and it can get token ok
but can i user android library for create customer and store card to customer  or I just get token by android library and sent it to server site for create customer  and store card to customer 

i saw in README.md
" This library also allows you to securely store customers card data and can be used for their next payment with out input it again "
but i can not saw in example 

Thank you so much
Adisak.

**Comment by robinclart** [comment]
Hi Adisak, you'll need to send the token to your web server. This is required since you must not publish your app with your secret key for security reason. Since you need that key to create the customer it is not feasible to allow customer creation from either this library or the iOS one.

**Comment by robinclart** [comment]
We'll update the readme to reflect this. Thanks for the feedback ;)

**Comment by daisyfoto** [comment]
OK , thank you so much robinclart
