### ISSUE TITLE
Card Brand Logo For VISA and Mastercard are colored white

### ISSUE THREAD

**Issue by Yoshi3003** [omise/omise-android#21]
Hi,

It seems that the card brand logo (within the SDK) for VISA and MasterCard (at least) are white and not colored like the original. Not sure if this is intended ?

The resources are retrieved from the code below (as in CreditCardActivity):
`CardBrand.getLogoResourceId()`

Thank you,
Jitrapon

**Comment by pitiphong-p** [comment]
Yes, that is intended. Since the logo will be appeared on the card number input field which will have a dark background.
