### ISSUE TITLE
Google Play warning: com.google.android.gms:play-services-ads 18.3.0 is outdated

### ISSUE THREAD

**Issue by chalermpong** [omise/omise-android#256]
Hi

My app got this warning when submitting to Google Play Store. The warning came `omise-android` because it is using outdated `com.google.android.gms:play-services-ads 18.3.0`.

```
Dependencies output
+--- co.omise:omise-android:4.8.0
|    +--- co.omise:threeds-android:1.0.0-alpha11
|    |    +--- com.google.android.gms:play-services-ads:18.3.0
```

Full warning from Google Play:
> Warning
> 
> The developer of Google Mobile Ads (GMA) SDK (com.google.android.gms:play-services-ads) has reported version 18.3.0 as outdated. Consider upgrading to one of the following versions before publishing a new release: 19.2.0+.
> 
> Learn more about the SDKs that you're using and make informed SDK choices with [Google Play SDK Index](https://play.google.com/sdks).
> 
>  
> 
> Warning
> 
> The developer of Google Mobile Ads (GMA) SDK (com.google.android.gms:play-services-ads) added the following note to SDK version 18.3.0:
> 
> This version is officially deprecated, and will soon disable ad loading. Please update to a new version. See Deprecation and sunset  |  Android  |  Google Developers  for more details.
> 
> Learn more about the SDKs that you're using and make informed SDK choices with [Google Play SDK Index](https://play.google.com/sdks).
> 
>  
> 
> Warning
> 
> The developer of Google Mobile Ads (GMA) SDK (com.google.android.gms:play-services-ads-lite) has reported version 18.3.0 as outdated. Consider upgrading to one of the following versions before publishing a new release: 19.2.0+.
> 
> Learn more about the SDKs that you're using and make informed SDK choices with [Google Play SDK Index](https://play.google.com/sdks).

**Comment by danfowler** [comment]
Thanks for reporting. We'll take a look and come back with a timeline on a fix.

**Comment by aashishgurung** [comment]
Fixed by [#10](https://github.com/OmisePayments/3DS-ANDROID-SDK/pull/10)

**Comment by chalermpong** [comment]
@aashishgurung Will this #10 fix be available in the next release? 
Would be great if you could update this issue again when the fix be available on public release.

**Comment by aashishgurung** [comment]
@chalermpong Yes. it will be available in the next release. I will add update on this thread once we release the new version.
