### ISSUE TITLE
okhttp3.HttpUrl okhttp3.Request.url()' on a null object reference

### ISSUE THREAD

**Issue by loveleopard** [omise/omise-android#267]
Both the project and the third-party SDK use okhttp3 dependencies, resulting in an error in the interface call
implementation "co.omise:omise-android:4.10.0"

**Comment by nuxzero** [comment]
@loveleopard thank you for opening this issue. Could you provide these below information for helping investigate the issue please?
- Android Level API
- Omise-Android version
- Sample code of usage
- Error logs

**Comment by nuxzero** [comment]
I closed this issue for now. If you still face this issue feel free to reopen this issue.
