### ISSUE TITLE
bg_edit_text_outlined.xml    Compilation error

### ISSUE THREAD

**Issue by zhangwenxiang26** [omise/omise-android#268]
Android Studio->
	Android Studio Dolphin | 2021.3.1 Patch 1

AGP ->
	classpath 'com.android.tools.build:gradle:7.2.2'
	distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip

Omise Sdk ->
	implementation 'co.omise:omise-android:4.10.0'

The following errors are often encountered during Android Studio compilation

Unable to locate resourceFile (D:\.........\app\build\intermediates\merged-not-compiled-resources\google_dev\debug\drawable\bg_edit_text_outlined.xml) in source-sets.

bg_edit_text_outlined.xml , I found that it was only used in Omise Sdk.
![omise_error](https://github.com/omise/omise-android/assets/19923561/e0476a67-5c54-45a2-af4b-5452e57830b0)

I can temporarily resolve it through the following methods:
![omise_result](https://github.com/omise/omise-android/assets/19923561/6e810542-6c60-4124-bb49-5795051db1e8)

Can you help me check this issue?

**Comment by nuxzero** [comment]
@zhangwenxiang26 Thank you for opening this issue. However, we could not reproduce as you report. Could you try upgrade Android Studio to the latest version?

**Comment by zhangwenxiang26** [comment]
Okay, I will try according to your suggestion. I will temporarily close this issue.

**Comment by nuxzero** [comment]
Feel free to reopen this issue if you still face the same issue. 🙂
