### ISSUE TITLE
Samsung device space bar not added in CreditCardEditText

### ISSUE THREAD

**Issue by TheEnsis** [omise/omise-android#27]
I tested and it worked now for sony and asus device

**Comment by pitiphong-p** [comment]
Could you provide the device information? Model and Android version

**Comment by TheEnsis** [comment]
FYI : I added it it inside TextInputLayout

Devices I tested are samsung galaxy j5 version 6.0.1 and samsung note 5 version 7.0
Devices that work fine is sony XZs version 7.1 and asus zenphone version 6.0.1

**Comment by chakrit** [comment]
@nuxZERO please check if you can krub 🙇

**Comment by WeRockStar** [comment]
Huawei has same issue.

**Comment by nuxzero** [comment]
@WeRockStar What the model and Android version?

**Comment by WeRockStar** [comment]
@nuxzero Huawei P10 Plus and Android 7.0. I add EditText inside TextInputLayout (Floating Label)

**Comment by nuxzero** [comment]
@WeRockStar we already fixed about spacing on `CreditCardEditText `. Please checkout our new version `v2.6.2`.

Please don't hesitate to contract us If you has any problem.

**Comment by WeRockStar** [comment]
@nuxzero Thank you for support 🤘
