### ISSUE TITLE
Request to support screenshot and video recording prevention

### ISSUE THREAD

**Issue by nqtsparda** [omise/omise-android#270]
Hi team,

I notice the SDK doesnt support to set FLAG_SECURE to SDK activities
Payment applications nowadays require to prevent the app not to show Preview in Recent Apps and record video/screenshot in screens which have sensitive data like user payment information
So is there any plan to add SDK configuration to enable FLAG_SECURE in the future ?

**Comment by aashishgurung** [comment]
@nqtsparda We have implemented the fix and will include it in our next release.
