### ISSUE TITLE
Suspected Proguard issue : Warning:co.omise.android.ui.CreditCardActivity$ActivityTokenRequestListener: can't find referenced field 'int text_error_message' in program class co.omise.android.R$id

### ISSUE THREAD

**Issue by j2emanue** [omise/omise-android#33]
#When building a signed apk i get the following warning:

Warning:co.omise.android.ui.CreditCardActivity$ActivityTokenRequestListener: can't find referenced field 'int text_error_message' in program class co.omise.android.R$id

here are my gradle dependencies:

    implementation 'co.omise:omise-android:2.3.+'
    
adding the following to proguard does not rectify the warning:

```
# Omise
-dontwarn okio.**
-dontwarn com.google.common.**
-dontwarn org.joda.time.**
```

if it makes any difference we are also using the following dependencies:
```
//barcode scanner
        implementation 'com.journeyapps:zxing-android-embedded:3.5.0'
//card scanner
        implementation 'io.card:android-sdk:5.5.1'
```

        

and we have been using your sdk in production for many months now with no issue but we have task to clean this warning.

**Comment by nuxzero** [comment]
@j2emanue Can you try to change with our latest version `implementation 'co.omise:omise-android:2.6.2'`.

**Comment by j2emanue** [comment]
ill test it out shortly tomorrow

**Comment by j2emanue** [comment]
upgrading to the latest version has not resolved the issue.  After tryingt o build a signed apk i still get a lint warning of : `Warning:co.omise.android.ui.CreditCardActivity$c: can't find referenced field 'int text_error_message' in program class co.omise.android.R$id
`

below is the gradle dependency being used:

`implementation 'co.omise:omise-android:2.6.2'`

**Comment by nuxzero** [comment]
We tested in our sample app it look fine for signed apk. But you could try to add `-dontwarn co.omise.android.R$id`.

**Comment by j2emanue** [comment]
yeah ignoring it fixes the warning.
