### ISSUE TITLE
Alipay not redirect back to application on version 2.6.2

### ISSUE THREAD

**Issue by minibugdev** [omise/omise-android#34]
I think this issue was fixed on branch [handle-alipay-authorize-uri](https://github.com/omise/omise-android/tree/handle-alipay-authorize-uri) but not merged.

**Comment by nuxzero** [comment]
@minibugdev Thank you for your feedback. We are working on this issue and we will merge this issue to next version soon. 😄

**Comment by nuxzero** [comment]
@minibugdev Can you share for more information that will help us solve this issue?

**Comment by minibugdev** [comment]
Thanks @nuxzero, We are try to charge **Alipay** by using `AuthorizingPaymentActivity`as follow steps

* **1. Mobile Number**
![Step1. Mobile Number](https://i.imgur.com/Dbz6Yzo.png)

* **2. OTP**
![Step2. OTP](https://i.imgur.com/ob8P9Yw.png)

* **3. Open/Download Alipay**
![Step3. Open/Download Alipay](https://i.imgur.com/J3zoByX.png)
At this step, can not do anything.

**Comment by minibugdev** [comment]
@pitiphong-p , We build `handle-alipay-authorize-uri` and reproduce flow.
It work properly until submit OTP and application crash.

![Crash](https://i.imgur.com/LoCVCua.png)

**Comment by pitiphong-p** [comment]
You authorize payment via Alipay app or web browser?

**Comment by minibugdev** [comment]
I authorize payment via `AuthorizingPaymentActivity` and application crash when we submit an OTP.

This error was occurred before we proceed to step 3 (Open/Download Alipay) as I mentioned above.

**Comment by pitiphong-p** [comment]
Do you have an `Alipay` app installed on your phone?

**Comment by pitiphong-p** [comment]
So the app crashes before reaching step 3? You didn't see the step 3 scene during your test process?

**Comment by minibugdev** [comment]
I don't have `Alipay` app on my phone and app crashes before reaching step 3.

**Comment by pitiphong-p** [comment]
Thank you for the information. We'll investigate on this

**Comment by nuxzero** [comment]
@minibugdev Please you check the latest version. If you have any problem, please don't hesitate to ask us.
