### ISSUE TITLE
kakaopay/AlipayHK/Alipay   pay ->  Failure(throwable=co.omise.android.OmiseException: Open deep link failed);

### ISSUE THREAD

**Issue by zhangwenxiang26** [omise/omise-android#354]
### Expected behavior

After entering the AuthorizingPaymentActivity  page, if the mobile device does not have the corresponding payment app installed, a UI is displayed to prompt the user to choose whether to download the payment app, instead of automatically throwing an exception and ending the AuthorizingPaymentActivity  page.

Touch‘n Go  is ok !!

### Actual behavior

After entering the AuthorizingPaymentActivity  page, Opn payments automatically open the payment app, If the payment app is not installed, the AuthorizingPaymentActivity page will end.   The merchant's payment page will receive an error message：Failure(throwable=co.omise.android.OmiseException: Open deep link failed).

### Steps to reproduce the issue

kakaopay  pay ->  entering the AuthorizingPaymentActivity 

### Name and version information

Android Studio : Hedgehog | 2023.1.1 Patch 2;

Opn Sdk : co.omise:omise-android:5.1.0 ;

Device ：OPPO PDKM00  Android 12

**Comment by aashishgurung** [comment]
@zhangwenxiang26 Thank you for reaching out. We will look into this and provide an update when we resolve this. Thank you.
