### ISSUE TITLE
Saving customer card details

### ISSUE THREAD

**Issue by hamzabinamin** [omise/omise-android#39]
Is it possible to save the customer card details (name, card number, cvv and expiry) on the client side using the android sdk?

**Comment by nuxzero** [comment]
Sorry, we are not recommended to save card details on client side. Please checkout our documentation about collecting cards.
- https://www.omise.co/security-best-practices
- https://www.omise.co/collecting-card-information
- https://www.omise.co/customers-api#create-a-customer

**Comment by hamzabinamin** [comment]
@nuxzero Thanks for the reply. I was able to create customers, however I was wondering how can I retrieve a particular customer. I understand that I can use something like the following:

$customer = OmiseCustomer::retrieve('cust_test_4xtrb759599jsxlhkrb');

But how can I store the customer ID (cust_test_4x...) so that I can reference that customer later on? I am using PHP on the server end and android on the client side.

**Comment by chakrit** [comment]
@hamzabinamin This is unrelated to omise-android. Please make an issue on omise/omise-php repository or on the public forum https://forum.omise.co
