### ISSUE TITLE
Using real debit/credit cards to make test transactions

### ISSUE THREAD

**Issue by hamzabinamin** [omise/omise-android#42]
Is it possible to use real debit/credit cards to make test transactions without deducting the balance from the cards?

**Comment by nuxzero** [comment]
Yes, you can test with real debit/credit cards in test mode.

**Comment by hamzabinamin** [comment]
@nuxzero Thanks for the reply. Could you please let me know if my flow of using the gateway is correct?

1. Capturing Card Details using my own card form.
2. Creating the client object.
3. Creating the token request object and saving the card details
4. Then using the client request to send that token request. 
5. The received token is used to create the customer object in omise and I'm then saving that customer 
  ID in my own db as well in order to reference the card for future use.  

How can I then use this token to charge the client for a certain amount, lets say THB 50?

**Comment by nuxzero** [comment]
- Your flow look corrected.
- If you need to use token to  charge the client. You need to implement charge on server side with Charge API https://www.omise.co/charging-cards.

**Comment by hamzabinamin** [comment]
@nuxzero Is it possible to do the charge directly through the android SDK? Will all cards get charged successfully or will some require 3d secure as well?

**Comment by nuxzero** [comment]
Q: Is it possible to do the charge directly through the Android SDK?
A: We does not provide SDK to make a charge on the client side. Our SDK provides Tokenization API to avoid sent credit card data to server-side https://www.omise.co/tokens-api. 

Q: Will all cards get charged successfully or will some require 3d secure as well?
A: This depends on your account in approval KYC.

**Comment by hamzabinamin** [comment]
@nuxzero 
Q: But how can I charge  an amount using the Tokenization API?
Q: What is approval KYC?

**Comment by chakrit** [comment]
@hamzabinamin The Tokenization API is not for charging. You can use the Charge API for that, which must be called from the server-side. The `skey` required to do so can also be used to make money transfer and perform other sensitive actions.

Please check [Collecting Cards](https://www.omise.co/collecting-card-information) docs for more info.

![](https://cdn.omise.co/assets/developer-documents/images_jpg/small_token@2x.jpg)

**Comment by chakrit** [comment]
@hamzabinamin For 3DS, this depends on your account settings and our KYC (know-your-customer) process when you apply for a live account. We require some merchants to enable 3DS to reduce fraud risk. Merchants who have 3DS enabled on their account will always have to do an authorization redirect. Otherwise, there will be no authorization step needed for credit cards and you can always charge in one HTTP call (provided you already have the token from your mobile app.)

**Comment by chakrit** [comment]
If you need more information about the KYC process or whether or not you need to worry about 3DS, please check with our support team: support@omise.co

**Comment by hamzabinamin** [comment]
Hi there, we are looking to launch the app, I would like to convert the testing account into live account. What is the process for that? Currently I have used real credit cards using the Charge API and it works without enabling 3DS or any additional security. Should we expect the same behavior in the live environment? How can we check that?

**Comment by nuxzero** [comment]
@hamzabinamin, here are answers to your questions.


**I would like to convert the testing account into live account. What is the process for that?**
- You need to activate your live account by visiting https://dashboard.omise.co/registrations

**Currently, I have used real credit cards using the Charge API and it works without enabling 3DS or any additional security. Should we expect the same behaviour in the live environment? How can we check that?**
- You shouldn't expect the same behaviour about 3DS or any additional security in the live environment. If your account enable 3DS or required to enable it then you need to handle that case in the live environment. However, you can simulate the 3DS-like process by providing the `authorize_url` parameter when creating a charge in test mode

**How can we check that?**
- You can check from the dashboard in live mode it should have transactions after you do a charge.


If you have any problem or question please don't hesitate to ask for help.
