### ISSUE TITLE
omise android sdk

### ISSUE THREAD

**Issue by SagarRaiyani** [omise/omise-android#5]
Hello sir / ma'am,

I have working omise payment gateway integration in our application but the sample SDK some import not found, so please check my screen-sort and give me a suggestion..
![capture](https://cloud.githubusercontent.com/assets/5584295/6228898/7340e9b6-b6d7-11e4-801a-b3fd9cf458aa.PNG)

**Comment by robinclart** [comment]
Hi @SagarRaiyani, that's our fault. We forgot to update the example after we change the SDK. All code related to Customer have been dropped for security reason. Sorry about that.

**Comment by SagarRaiyani** [comment]
Hello @robinclart, thanks for reply..   :)

**Comment by robinclart** [comment]
You're welcome. We have updated the Example. It should work now. You can just `git pull` the change.
