### ISSUE TITLE
Use of CreditCard activity

### ISSUE THREAD

**Issue by shroff-kandarp** [omise/omise-android#50]
Please use appcompact activity. This is required to have material theme with toolbar with style. Also please support to light theme also. Currently background is black. If we change it to light then spinner item text is not showing.

**Comment by nuxzero** [comment]
Sorry for the unfortunate, the OmiseAndroid did not support the support library at the moment. You can create your own credit card page with the support library or AndroidX to support your requirement. Our team will consider your suggestion and discuss this more internally.

**Comment by shroff-kandarp** [comment]
If we use custom form then Is PCI-DSS required on our server? 
Our flow Of custom form will be followed as below: We are using token payment.
1- Custom form
2- Entered details are directly pass to your server through your SDK
3 - Your sdk gives us token for that card details.
4 - This token is passed to our server for creating future payment.

Do we require PCI-DSS on our server?

**Comment by shroff-kandarp** [comment]
okay thanks.
