### ISSUE TITLE
Wrong CardBrand Identification

### ISSUE THREAD

**Issue by trungnn307** [omise/omise-android#80]
I got this MasterCard test 2221 0000 0000 0009. In iOS version, the CreditCardText can identify that is MasterCard but in Android it can't  https://prnt.sc/p214ux

**Comment by nuxzero** [comment]
@trungnn307 Thank you for your report. We investigated and found that your testing number was in the newly added available BIN list for MasterCard but our Omise Android SDK doesn't have an information about them. We are aware of this issue now and will fix it in the future version.
