### ISSUE TITLE
Charge Class not found as you mention in Charge api

### ISSUE THREAD

**Issue by VIjendraSalve** [omise/omise-android#96]
Request<Charge> createChargeRequest = new Charge.CreateRequestBuilder()
        .amount(100000)
        .currency("THB")
        .card(token.getId())
        .build();
Charge charge = client().sendRequest(createChargeRequest);

in this code Charge class not found in sdk

**Comment by pitiphong-p** [comment]
Hi @VIjendraSalve, Omise doesn't encourage a merchant to create a charge on the client due to the security concern. The recommend approach is to create a token with Omise Android SDK and then send the Token ID to the merchant backend and create a charge from there.

**Comment by VIjendraSalve** [comment]
can you explain me what is the procedure for  to create a token with Omise
Android SDK and then send the Token ID to the merchant backend and create a
charge from there.
or can you share me web page link to refer this.
Thanks in advance

**Comment by pitiphong-p** [comment]
A merchant need to have a server to communicate with Omise API and the credit card data must not be sent to their server. You can tokenize the credit card information on the client using Omise Android SDK which you will get a Token data then you can send you token ID to your server and have your server to communicate to create charge with Omise API

You can see more information on https://www.omise.co/collecting-card-information

**Comment by VIjendraSalve** [comment]
Thanks for your reply, but i already did the above procedure that you
mentioned in your last email so can you please explain me what is next
procedure after getting token id from card validation. with web page
reference.

**Comment by pitiphong-p** [comment]
You need to send the Token ID to your server and have your server to call Omise API to create a charge via the Charge API https://www.omise.co/charges-api

**Comment by VIjendraSalve** [comment]
Sorry to respond you late, but you are just giving us web page link their
is JSON response code but i cant find out input parameter with url so can
you please help me out with that.

**Comment by igroomgrim** [comment]
You can find in [Create a charge - Section](https://www.omise.co/charges-api#create).
We provide examples to create a charge below this section.
![create_charge_examples](https://user-images.githubusercontent.com/1023290/66022760-2b01eb80-e519-11e9-8a25-edfe237eafd1.PNG)
🙇

**Comment by VIjendraSalve** [comment]
Request<*Charge*> request = new Charge.CreateRequestBuilder()

        .amount(20000)
        .currency("THB")
        .description("That t-shirt")
        .card("card_test_4xtsoy2nbfs7ujngyyq")
        .build();
*Charge *charge = client.sendRequest(request);

System.out.printf("Created charge: " + charge.getId());

We are using this one for android to send amount but this *Charge
Class* is not available in your sdk or is their any other
dependencies?

we already integrated below dependency :

implementation 'co.omise:omise-android:2.6.6'
implementation 'io.card:android-sdk:5.4.0'

**Comment by nuxzero** [comment]
Sorry, this example is for `omise-java` dependency on the server side for the case that you implement your server in Java.

**Comment by VIjendraSalve** [comment]
So how can we send data from android app. I mean which api format we have
to use?

**Comment by nuxzero** [comment]
You can check from explained in above https://github.com/omise/omise-android/issues/96#issuecomment-535772972 🙂
